In [1]:
a = 1
print(a)
b = 1.1
print(b)


1
1.1


In [3]:
a=1
b=1
print(id(a))

4314243688


In [5]:
c=1
print(id(c))

4314243688


In [7]:
num = int(input("Enter a number: "))

print("Table of", num, ":")

for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

WA function that gives sum, avg, min and max of all the input are given


SyntaxError: invalid syntax (540859819.py, line 8)

In [9]:
/#a user has a 3x3 and then in the copied matrix multiply each value by a constant and store the result in place after this print both the matrix.
import numpy as np
original_matrix = np.array([
    [1,2,3],
    [2,4,6],
    [7,8,9]
])

a = 5
modified_matrix = original_matrix * a
print(original_matrix)
print(modified_matrix)

[[1 2 3]
 [2 4 6]
 [7 8 9]]
[[ 5 10 15]
 [10 20 30]
 [35 40 45]]


In [11]:
def sum2(a,b,c):
    print (a,b,c)
    res = a + b + c
    return res

result = sum2(1,2,3)
print(f"result is {result}")


1 2 3
result is 6


In [ ]:
write a function that take one variable as inpout and return it sum , cumulative sum, average , min and maximum value. implement this function using for loop.  define function documentation using docstring and show its uses

In [28]:
def calculate_stats(numbers):
    
   
    sum_value = sum(numbers)
    cumulative_sum = [sum(numbers[:i+1]) for i in range(len(numbers))]
    average = sum_value / len(numbers)
    min_value = min(numbers)
    max_value = max(numbers)
    print(f"sum is ->{sum_value}")
    print(f"cumulative is ->{cumulative_sum}")
    print(f"average is ->{average}")
    print(f"minimum is ->{min_value}")
    print(f"maximum is ->{max_value}")


In [30]:
def newlist():
    length= int(input("Enter the number of elements you want in the list: "))
    list1=[]
    for i in range(0, length):
        number = int(input(f"Enter the {i} Element in the list: "))
        list1.append(number)
    calculate_stats(list1)

newlist()

Enter the number of elements you want in the list:  5
Enter the 0 Element in the list:  5
Enter the 1 Element in the list:  6
Enter the 2 Element in the list:  7
Enter the 3 Element in the list:  8
Enter the 4 Element in the list:  8


sum is ->34
cumulative is ->[5, 11, 18, 26, 34]
average is ->6.8
minimum is ->5
maximum is ->8
